### ISSUE TITLE
`npx amplify-app@latest` gives "Error: Cannot find module 'amplify-frontend-javascript'"

### ISSUE THREAD

**Issue by gabehollombe-aws** [aws-amplify/docs#1123]
**Describe the bug**
When following the steps outlined here to get started with Amplify DataStore: https://aws-amplify.github.io/docs/js/datastore#using-npx

I receive this error: `Error: Cannot find module 'amplify-frontend-javascript'`

**Note: Using previous version `npx amplify-app@2.13.0` works**

Full terminal transcript output of the error is below.

**To Reproduce**
Full transcript:
```
➜  /tmp npx create-react-app amplify-datastore --use-npm
cd amplify-datastore
npx amplify-app@latest

npx: installed 91 in 6.111s

Creating a new React app in /private/tmp/amplify-datastore.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...


> fsevents@1.2.11 install /private/tmp/amplify-datastore/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.11 install /private/tmp/amplify-datastore/node_modules/jest-haste-map/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@2.6.11 postinstall /private/tmp/amplify-datastore/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.4 postinstall /private/tmp/amplify-datastore/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.4 postinstall /private/tmp/amplify-datastore/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

+ cra-template@1.0.0
+ react@16.12.0
+ react-scripts@3.3.0
+ react-dom@16.12.0
added 1682 packages from 766 contributors and audited 911004 packages in 62.173s
found 0 vulnerabilities


Installing template dependencies using npm...
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

+ @testing-library/react@9.4.0
+ @testing-library/jest-dom@4.2.4
+ @testing-library/user-event@7.2.1
added 17 packages from 41 contributors and audited 911176 packages in 8.893s
found 0 vulnerabilities

Removing template package using npm...

npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

removed 1 package and audited 911175 packages in 6.443s
found 0 vulnerabilities


Initialized a git repository.

Success! Created amplify-datastore at /private/tmp/amplify-datastore
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd amplify-datastore
  npm start

Happy hacking!
npx: installed 94 in 5.767s
✅ Found Amplify CLI version 4.13.1
🎸 Creating base Amplify project
Error: Cannot find module 'amplify-frontend-javascript'
Require stack:
- /Users/REDACTED/.npm/_npx/54281/lib/node_modules/amplify-app/src/index.js
- /Users/REDACTED/.npm/_npx/54281/lib/node_modules/amplify-app/bin/amplify-app
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/REDACTED/.npm/_npx/54281/lib/node_modules/amplify-app/src/index.js:185:31
    at Array.forEach (<anonymous>)
    at guessPlatform (/Users/REDACTED/.npm/_npx/54281/lib/node_modules/amplify-app/src/index.js:184:20)
    at getProjectConfig (/Users/REDACTED/.npm/_npx/54281/lib/node_modules/amplify-app/src/index.js:151:51)
    at ChildProcess.<anonymous> (/Users/REDACTED/npm/_npx/54281/lib/node_modules/amplify-app/src/index.js:115:18)
    at ChildProcess.emit (events.js:210:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/REDACTED/.npm/_npx/54281/lib/node_modules/amplify-app/src/index.js',
    '/Users/REDACTED/.npm/_npx/54281/lib/node_modules/amplify-app/bin/amplify-app'
  ]
}
```
**Expected behavior**
I expect the command to finish without an error.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6

**Comment by nikhname** [comment]
Closing by https://github.com/aws-amplify/amplify-cli/pull/3312
