### ISSUE TITLE
Amplify Android : Getting Started Doc : Amplify Init fails before amplify push

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/docs#1779]
# Android Getting Started Doc 

## Step 3 : Integrate in your App 

**URL** : https://next-docs.amplify.aws/lib/getting-started/integrate/q/platform/android#configure-amplify-and-datastore

Amplify can not be initialized before an `amplify push`
Steps in the doc says to add Amplify Initialization code and then run the app.
Run fails with 

```text
E/.newsblog.myap: Invalid ID 0x00000000.
E/Tutorial: Could not initialize Amplify
    AmplifyException {message=Failed to find amplifyconfiguration., cause=android.content.res.Resources$NotFoundException: Resource ID #0x0, recoverySuggestion=Please check that it has been created.}
        at com.amplifyframework.core.AmplifyConfiguration.fromConfigFile(AmplifyConfiguration.java:24)
        at com.amplifyframework.core.AmplifyConfiguration.fromConfigFile(AmplifyConfiguration.java:3)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:1)
        at com.amazonaws.newsblog.myapp.MainActivity.onCreate(MainActivity.kt:29)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
        at android.content.res.ResourcesImpl.openRawResource(ResourcesImpl.java:324)
        at android.content.res.Resources.openRawResource(Resources.java:1281)
        at android.content.res.Resources.openRawResource(Resources.java:1225)
        at com.amplifyframework.core.AmplifyConfiguration.fromConfigFile(AmplifyConfiguration.java:5)
        at com.amplifyframework.core.AmplifyConfiguration.fromConfigFile(AmplifyConfiguration.java:3) 
        at com.amplifyframework.core.Amplify.configure(Amplify.java:1) 
        at com.amazonaws.newsblog.myapp.MainActivity.onCreate(MainActivity.kt:29) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

At this stage, an `amplify status` fails too

```text
➜  amplify-lib-android-demo amplify status
| Category | Resource name     | Operation | Provider plugin   |
| -------- | ----------------- | --------- | ----------------- |
| Api      | amplifyDatasource | Create    | awscloudformation |

ENOENT: no such file or directory, open '/Users/stormacq/Documents/amazon/code/amplify/amplify-lib-android-demo/amplify/backend/amplify-meta.json'
Error: ENOENT: no such file or directory, open '/Users/stormacq/Documents/amazon/code/amplify/amplify-lib-android-demo/amplify/backend/amplify-meta.json'
    at Object.openSync (fs.js:461:3)
```

The `amplify/backend/amplify-meta.json` is created after a `modelPush` and Amplify Initialization works only after `amplifyPush`

**Step** : type `amplify push`or choose `amplifyPush` target and click `build`. 
**Result** : 

```text
I/Tutorial: Initialized Amplify
I/amplify:aws-datastore: Creating table: PersistentModelVersion
I/amplify:aws-datastore: Creating table: Todo
I/amplify:aws-datastore: Creating table: PersistentRecord
I/amplify:aws-datastore: Creating table: LastSyncMetadata
I/amplify:aws-datastore: Creating table: ModelMetadata
I/amplify:aws-datastore: Creating index for table: PersistentRecord
```

After doing an amplify push, the examples work (init, save, query)

**Comment by jpignata** [comment]
Awesome, thanks! We actually were trying to get this working without a push. I'm updating the docs now to work around this issue.

**Comment by jpignata** [comment]
Addressed in the latest revision. Let us know and thanks!
