### ISSUE TITLE
`amplify configure` was failed.

### ISSUE THREAD

**Issue by saintsouth** [aws-amplify/docs#2130]
**Page**: [`/start/q/integration/angular`](https://docs.amplify.aws/start/q/integration/angular)

**Feedback**:

I tried new amplify project "tutorial".
I read this page, and execute `amplify configure`, but it was failed.

Error on my console.
```
Cannot read property 'v4' of undefined
TypeError: Cannot read property 'v4' of undefined
    at new UsageDataConfig (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/app-config/config.js:52:48)
    at new Config (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/app-config/config.js:38:32)
    at Function.get Instance [as Instance] (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/app-config/config.js:42:29)
    at Object.init (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/app-config/config.js:23:27)
    at Object.attachUsageData (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/context-manager.js:16:33)
    at Object.run (/home/user/tutorial/node_modules/@aws-amplify/cli/lib/index.js:68:33)
```

My environment.
```
$ node -v
v12.18.2
$ npm -v
6.14.5
```

**Comment by mauerbac** [comment]
@gsans , would you be able to help here?

**Comment by gsans** [comment]
Sure. It seems that the error message points to a missing dependency in the CLI source for the uuid package. 

```
this.installationUuid = uuid.v4();
```

https://github.com/aws-amplify/amplify-cli/blob/4d217af830e04d7157d65e14f25af6c39d0315de/packages/amplify-cli/src/app-config/config.ts#L54

**Comment by gsans** [comment]
@saintsouth I would first try these steps
```
npm install -g @aws-amplify/cli
amplify configure
```
If the above fails I would try a version before the latest with
```
npm install -g @aws-amplify/cli@4.23.1
amplify configure
```
Let me know if that worked
