### ISSUE TITLE
DataStore fails to codegen models when using @connection for 1 to 1 on @key with no name

### ISSUE THREAD

**Issue by ericowhadi** [aws-amplify/docs#2460]
**Describe the bug**
 codegen on the following schema works:
```graphql
type Video @model  @key(fields: ["id","companyId","studyId","version"]){
  id: ID!
  companyId: String! 
  studyId: ID! 
  version: String!
  masterId: ID!
  masterVersion: String! 
  s3Url: String
  sentences: [Sentence!] @connection(keyName: "byVideo", fields: ["id","companyId","studyId","version"])
 #masterVideo: Video @connection(fields: ["id","companyId","masterId","masterVersion"])
}

type Sentence @model  @key(fields: ["id", "index"])
@key(name: "byVideo", fields: ["videoId","companyId","studyId","version"]){
  id: ID!
  index: String!
  videoId: ID! 
  companyId: String! 
  studyId: ID! 
  version: String! 
  tt: String!
#parentVideo: Video @connection (fields:  ["videoId","companyId","studyId","version"])
} 
```

if I uncomment ether of the commented one to one @connection, I get error below when doing codegen (while the amplify pushed schema works).

//uncommenting #parentVideo:
DataStore only support one key in field
Error: DataStore only support one key in field
    at Object.processConnections (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\utils\process-connections.ts:144:17)
    at C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:448:32
    at Array.forEach (<anonymous>)
    at C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:447:20
    at Array.forEach (<anonymous>)
    at AppSyncModelJavascriptVisitor.processConnectionDirective (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:446:34)
    at AppSyncModelJavascriptVisitor.processDirectives (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:241:10)
    at AppSyncModelJavascriptVisitor.generate (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-javascript-visitor.ts:48:10)
    at Object.exports.plugin (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\plugin.ts:49:20)
    at Object.executePlugin (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\@graphql-codegen\core\src\execute-plugin.ts:54:12)
	
//uncommenting #masterVideo
DataStore only support one key in field
Error: DataStore only support one key in field
    at Object.processConnections (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\utils\process-connections.ts:144:17)
    at C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:448:32
    at Array.forEach (<anonymous>)
    at C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:447:20
    at Array.forEach (<anonymous>)
    at AppSyncModelJavascriptVisitor.processConnectionDirective (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:446:34)
    at AppSyncModelJavascriptVisitor.processDirectives (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-visitor.ts:241:10)
    at AppSyncModelJavascriptVisitor.generate (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\visitors\appsync-javascript-visitor.ts:48:10)
    at Object.exports.plugin (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen-appsync-model-plugin\src\plugin.ts:49:20)
    at Object.executePlugin (C:\Users\owhadi\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\@graphql-codegen\core\src\execute-plugin.ts:54:12)

Amplify Doc on dataStore specify this:
When using the @key directive with DataStore, as long as you specify a name you can use any value(s) in fields. However, if the name property is omitted, the first item in the fields array must be "id". E.g., @key(fields: ["id", "content"]).
This hint that what I am doing should work, and therefore this is a bug.

**Amplify CLI Version**
4.27.3

**To Reproduce**
see above, just uncomment one of the commented line and try amplify codegen models

**Expected behavior**
amplify codegen models should successfully generate code.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. v12.18.1

**Additional context**

**Comment by jhockett** [comment]
We've added an additional warning to the graphql section in the CLI at the bottom of Has-One: https://docs.amplify.aws/cli/graphql-transformer/connection#has-one

We plan to make this more obvious in the coming weeks. cc @iartemiev

**Comment by pagameba** [comment]
The current documentation is not actually correct

> A Has One @connection can only reference the primary index of a model (ie. it cannot specify a “keyName” as described below in the Has Many section).

I have a table with a hash and sort key for the primary index and it is not letting me specify two fields to pass for the primary key.  This is a shortened version of what I have set up.  It is the addition of `secondaryKey` to the connection that is causing the problem, even though this is the primary key for the User table (combining the id and the secondaryKey.  In my case, the id is not unique unless combined with the secondaryKey.

```
type User @model @key(fields: [ "id", "secondaryKey" ]) {
  id: ID!
  secondaryKey: ID!
}

type Group @model {
  id: ID!
}

type GroupMembership @model @key(fields: [ "userId", "groupId" ]) {
  userId: ID!
  groupId: ID!
  secondaryKey: ID!
  user: [User] @connection(fields: [ "userId", "secondaryKey" ])
  group: Group @connection(fields: [ "groupId" ])
}

**Comment by pagameba** [comment]
I think this should be kept open, it is still a bug as far as I'm concerned.

**Comment by htc007** [comment]
I understand that DataStore currently doesn't support a composite primary key as @pagameba has done in his schema.

However, correct me if I'm wrong, but we should be able to use Amplify's GraphQL Client (and the auto-generated models) **WITHOUT** using DataStore.

In our case:
1. We have a composite primary key
2. We want to interact with our API using Amplify's GraphQL Client
3. We have no intention of using DataStore

Why is a DataStore error preventing models from being generated for use with Amplify's GraphQL Client?

If you're going to prevent models from being generated simply because of a DataStore error, then you can't say that the GraphQL Client can be used on its own without DataStore.

**Comment by pagameba** [comment]
I'd also like to bump this issue again, since it is a perfectly valid and in fact encouraged design pattern with dynamodb to have a primary key composed of two fields. Our workaround is that the connection has to resolve to an array of objects, which in practice will always contain exactly one object. While this works, it makes front end code access properties quite messy and unnecessarily confusing.

**Comment by chrisbonifacio** [comment]
Closing this issue as we now support custom primary and composite keys in DataStore. We've also since upgraded our graphql transformer to support more intuitive directives such as `@primaryKey`, `@index`, `@hasOne`, `@hasMany`, etc. Please upgrade to the latest versions of the Amplify CLI and Amplify JS library to use these features.
