### ISSUE TITLE
Amplify Appsync websockets and subscriptions not working or not reliable

### ISSUE THREAD

**Issue by BernhardSmuts** [aws-amplify/docs#2712]
@dabit3 
@jamesonwilliams 
**Page**: 
[`/start/q/integration/js`](https://docs.amplify.aws/start/q/integration/js)

**Feedback**:
I have been working with Amplify Appsync's subscriptions for the past week now. 
Everything was working fine up until yesterday. 

I have a system that would subscribe to transactions made by specific stores in a transactions table. This was all working fine. 

In the last two days I am constantly getting the following error in my web console:
```javascript
WebSocket connection to 'wss://xvve3nh62rfwnepazctkj7h2ge.appsync-realtime-api.us-east-2.amazonaws.com/graphql?header=eyJob3N0IjoieHZ2ZTNuaDYycmZ3bmVwYXpjdGtqN2gyZ2UuYXBwc3luYy1hcGkudXMtZWFzdC0yLmFtYXpvbmF3cy5jb20iLCJ4LWFtei1kYXRlIjoiMjAyMDExMjZUMTE1ODAwWiIsIngtYXBpLWtleSI6ImRhMi1kMmpjZGxtem9qYWtmYnAyaXZlbGNzZGl3YSJ9&payload=e30=' failed: Error during WebSocket handshake: net::ERR_SSL_PROTOCOL_ERROR
```

This repeats about 6 times as I am assuming the websocekt tried to reconnect, ending with this message:

```javascript
Uncaught {provider: AWSAppSyncRealTimeProvider, error: {…}}error: errors: Array(1)0: {message: "Connection failed: Connection handshake error"}length: 1__proto__: Array(0)__proto__: Objectprovider: AWSAppSyncRealTimeProviderawsRealTimeSocket: nullisSSLEnabled: (...)keepAliveTimeout: 300000options: (...)promiseArray: []socketStatus: 0subscriptionObserverMap: Map(0) {}_config: {}__proto__: Object__proto__: AbstractPubSubProvider__proto__: Object
(anonymous) @ Observable.js:65
setTimeout (async)
hostReportError @ Observable.js:64
notifySubscription @ Observable.js:149
onNotify @ Observable.js:179
error @ Observable.js:240
error @ PubSub.ts:176
notifySubscription @ Observable.js:140
onNotify @ Observable.js:179
error @ Observable.js:240
(anonymous) @ AWSAppSyncRealTimeProvider.ts:296
step @ AWSAppSyncProvider.ts:204
(anonymous) @ AWSAppSyncProvider.ts:204
rejected @ AWSAppSyncProvider.ts:204
Promise.then (async)
step @ AWSAppSyncProvider.ts:204
fulfilled @ AWSAppSyncProvider.ts:204
Promise.then (async)
step @ AWSAppSyncProvider.ts:204
fulfilled @ AWSAppSyncProvider.ts:204
Promise.then (async)
step @ AWSAppSyncProvider.ts:204
(anonymous) @ AWSAppSyncProvider.ts:204
push../node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js.__awaiter @ AWSAppSyncProvider.ts:204
AWSAppSyncRealTimeProvider._startSubscriptionWithAWSAppSyncRealTime @ AWSAppSyncRealTimeProvider.ts:227
(anonymous) @ AWSAppSyncRealTimeProvider.ts:185
Subscription @ Observable.js:197
subscribe @ Observable.js:279
(anonymous) @ PubSub.ts:173
(anonymous) @ PubSub.ts:172
Subscription @ Observable.js:197
subscribe @ Observable.js:279
subAllToDos @ App.js:30
(anonymous) @ App.js:42
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:590
flushWork @ scheduler.development.js:545
performWorkUntilDeadline @ scheduler.development.js:157
```
I then tried to just run it purely in Appsync's console and I get the same errors in the console, with this error in appsync's output window:

```javascript
Error: {
    "errors": [
        {
            "message": "Connection failed: Connection handshake error"
        }
    ]
}
    at Object.error (https://d3owqdqy53mge.cloudfront.net/4e0034b0d516077971e58313cecbbabc76608841/main.js:135:859689)
    at d (https://d3owqdqy53mge.cloudfront.net/4e0034b0d516077971e58313cecbbabc76608841/main.js:203:1070669)
    at m (https://d3owqdqy53mge.cloudfront.net/4e0034b0d516077971e58313cecbbabc76608841/main.js:203:1071013)
    at e.value (https://d3owqdqy53mge.cloudfront.net/4e0034b0d516077971e58313cecbbabc76608841/main.js:203:1072095)
    at n.<anonymous> (https://d3owqdqy53mge.cloudfront.net/4e0034b0d516077971e58313cecbbabc76608841/main.js:135:679765)
    at r (https://d3owqdqy53mge.cloudfront.net/4e0034b0d516077971e58313cecbbabc76608841/main.js:135:675841)
    at Object.throw (https://d3owqdqy53mge.cloudfront.net/4e0034b0d516077971e58313cecbbabc76608841/main.js:135:675176)
    at s (https://d3owqdqy53mge.cloudfront.net/4e0034b0d516077971e58313cecbbabc76608841/main.js:135:674969)
```

The app I had built was using cognito userpools to auth. I also tried it on the subs in one of my previously built amplify apps, same issues.
 I even went as far as to rebuild an entire app from scratch following the `ToDo` getting started tutorial in the amplify docs, and the exact same errors occur. 
I have checked all the IAM roles and everything seems fine...

Strange this is that once in a while it might connect and then the subscription works fine, without changing anything, simply refreshing the page. Or rerunning the sub in Appsync console.

My internet speeds are fine, so not sure if that could be the issue:
Ping: 20ms
down: 15.07
up: 4.20

I really have no idea how to fix this?

**Comment by BernhardSmuts** [comment]
I seem to have found something.

When I switch to my mobile internet, it works fine. When I switch to my home internet it doesn't work reliably. So I think the issue is on my side. Leaving this here incase it helps someone else with this issue.
