### ISSUE TITLE
Error with Sample Rest API Setup

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/docs#2753]
1. Following the online instructions for setting up Rest API results in a non functioning project.  https://docs.amplify.aws/lib/restapi/getting-started/q/platform/android#initialize-amplify-api
2. 4.37.1
3. Same code as provided online except I use use path items instead of todo:
```
val options = RestOptions.builder()
    .addPath("/items")
    .addBody("{\"name\":\"Mow the lawn\"}".toByteArray())
    .build()

Amplify.API.post(options,
    { Log.i("MyAmplifyApp", "POST succeeded: $it") },
    { Log.e("MyAmplifyApp", "POST failed.", it) }
)
```
4. When I run the post request I get this error: 
```

2020-12-07 09:49:58.260 18936-19071/com.example.restapi E/MyAmplifyApp: POST failed.
    AmplifyException {message=Received an IO exception while making the request., cause=java.io.IOException: Failed to read credentials to sign the request., recoverySuggestion=Retry the request.}
        at com.amplifyframework.api.aws.operation.AWSRestOperation$OkHttpCallback.onFailure(AWSRestOperation.java:131)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.IOException: Failed to read credentials to sign the request.
        at com.amplifyframework.api.aws.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:202)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: com.amazonaws.AmazonClientException: Failed to get credentials from Cognito Identity
        at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:374)
        at com.amplifyframework.api.aws.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:194)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 7688d7be-9c6c-4e0e-8de5-64271e4d0640)

```
5. Any relevant guides or documentation you're referencing: All code and CLI setup based on amplify docs online. 

It appears the error is because I haven't used Amplify Cognito and pushed auth via the Amplify CLI.  However, there isn't any mention of adding this in the docs and during the cli instructions it says to allow unauthenticated access. 

![image](https://user-images.githubusercontent.com/11478656/101386982-b4762180-3872-11eb-9836-8d0f48071c97.png)

**Comment by fjnoyp** [comment]
Here is my generated amplifyconfiguration.json:

`{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "restapi": {
                    "endpointType": "REST",
                    "endpoint": "https://rp8260gmb3.execute-api.us-east-1.amazonaws.com/dev",
                    "region": "us-east-1",
                    "authorizationType": "AWS_IAM"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:c011d3ea-7add-4cc0-b089-0b4d043f9cea",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_ObxC7EWVC",
                        "AppClientId": "66ahcjmeqgvk456toh3rf6hmt2",
                        "AppClientSecret": "e693s987uo6l4egb2lvje6j0vr0uitjgg7mbr8g9cl0u1idfcdo",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}`

**Comment by jamesonwilliams** [comment]
Thanks @fjnoyp.

The docs do include a few references to Amplify Auth:

> Goal
> 
> To setup and configure your application with Amplify API to make requests to your API Gateway and trigger the lambda function using authorization provided by Amplify Auth.

> Initialize Amplify API
>
> To initialize the Amplify Auth and API categories you call Amplify.addPlugin() method for each category. 

However, the page _is_ missing:
1. Explicit code showing Auth integration
2. Links to supporting pages for setting up Auth
3. A pointed description of the dependency on Auth.

Note that the API category can be [setup to restrict access by API key, or to use no authorization at all](https://github.com/aws-amplify/amplify-android/blob/c425a4f1073b6245cf8fef18096c553e8fec99f2/aws-api/src/main/java/com/amplifyframework/api/aws/AuthorizationType.java#L24).

What values did you provide while going through `amplify add api`?

From here, I either recommend to:
1. Run `amplify update api`, and change the authorization strategy. Follow this with `amplify push`.
2. Run `amplify add auth`, and add a Cognito configuration that your API can leverage. I'm guessing you'll still have to run `amplify update api`, to make reference to it?

**Comment by fjnoyp** [comment]
When doing amplify add api, I don't see a NONE authorization option: 

![image](https://user-images.githubusercontent.com/11478656/101395554-f86f2380-387e-11eb-9a38-ef64694510e0.png)

**Comment by fjnoyp** [comment]
I can't seem to run `amplify update api,` doing so causes a crash in the cli: 

![image](https://user-images.githubusercontent.com/11478656/101395687-25233b00-387f-11eb-8d9b-301eaacd58ce.png)

**Comment by raphkim** [comment]
The CLI does not provide option to select `None` as your authorization option. Please try manually editing the `authorizationType` field inside your `amplifyconfiguration.json` to `"NONE"`. 

Meanwhile, there appears to be an error with the CLI flow that caused API to be configured with `AWS_IAM` restriction by default even when you specify "no" as a response to "Restrict API access". I will investigate this further and give an update.

**Comment by SwaySway** [comment]
@fjnoyp In regards to the stack error on API update. It looks like you added a GraphQL API as well. What was the flow in getting this error? Was it just on adding the GraphQL API and then doing an update?

**Comment by raphkim** [comment]
It appears that using CLI to add REST API to Amplify API restriction selection only allows choosing between IAM and Cognito User Pools as authorization. We will look into updating the docs for the time being to require adding Auth category.

> * Run amplify update api, and change the authorization strategy. Follow this with amplify push.
> * Run amplify add auth, and add a Cognito configuration that your API can leverage. I'm guessing you'll still have to run amplify update api, to make reference to it?

Since AWS_IAM auth mode simply requires Auth category to be configured, `amplify update api` command is not required in your case. `amplify add auth` and `amplify push` should suffice (as well as adding the auth plugin to Amplify via code)

> @fjnoyp In regards to the stack error on API update. It looks like you added a GraphQL API as well. What was the flow in getting this error? Was it just on adding the GraphQL API and then doing an update?

I also noticed that the screenshot you posted is showing GraphQL API addition CLI flow. Are you trying to use both, or was that an accident? `None` is not an option available because we do not allow insecure connection to the endpoints. Please try using `API_KEY` if you are hoping to get started quickly with GraphQL API setup without Auth category.

**Comment by jamesonwilliams** [comment]
It looks like the CLI generated an inoperable config and didn't render any queue to the user about what was going on. Instead it failed with an obscure error. IMO we should move this to the CLI project.
