### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by 1019459067** [aws-amplify/docs#3959]
**Page**: [`/lib/project-setup/create-application/q/platform/[platform]`](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios/#next-steps)

**Feedback**:

UnrecognizedClientException: The security token included in the request is invalid.
    at Object.extractError (/snapshot/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/snapshot/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/snapshot/node_modules/aws-sdk/lib/event_listeners.js:335:13)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'UnrecognizedClientException',
  time: 2022-01-23T03:02:34.835Z,
  requestId: 'b5b7578e-cb79-422d-822d-f697aba3b72a',
  statusCode: 403,
  retryable: false,
  retryDelay: 28.161231998129075
}

**Comment by mauerbac** [comment]
Hello @1019459067 - do you have details you can provide?
