### ISSUE TITLE
Vue 3 won't Build or Publish!

### ISSUE THREAD

**Issue by goldbergmoshe** [aws-amplify/docs#4359]
**Describe the bug**
When I try create a Vue 3 project with Amplify it serves without errors, however when you try publish or build I get the following errors;

ERROR  TypeError: ErrorStackParser.parse is not a function
TypeError: ErrorStackParser.parse is not a function
    at getOriginalErrorStack (/Users/moshetanzer/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:31:29)
    at extractError (/Users/moshetanzer/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:22:20)
    at Array.map (<anonymous>)
    at processErrors (/Users/moshetanzer/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/core/transformErrors.js:31:17)
    at FriendlyErrorsWebpackPlugin.displayErrors (/Users/moshetanzer/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:97:29)
    at doneFn (/Users/moshetanzer/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:57:14)
    at Hook.eval [as callAsync] (eval at create (/Users/moshetanzer/fullstack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/moshetanzer/fullstack/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/moshetanzer/fullstack/node_modules/webpack/lib/Compiler.js:498:23
    at Compiler.emitRecords (/Users/moshetanzer/fullstack/node_modules/webpack/lib/Compiler.js:919:5)
/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:174
		err = new Error(`Command failed: ${joinedCmd}${output}`);
		      ^

Error: Command failed: npm run build
    at makeError (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:174:9)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runNpmScript (/usr/local/lib/node_modules/@vue/cli/lib/util/runNpmScript.js:17:10) {
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm run build',
  timedOut: false,
  killed: false
}

Node.js v17.7.2

I think this is connected to the amplify ui library!
please help!

**To Reproduce**
follow the amplify guide here;

https://docs.amplify.aws/start/getting-started/data-model/q/integration/vue/#create-graphql-api-and-database

It just gives you an error when you try build

**Desktop (please complete the following information):**
MacOS Monatory

thanks!

**Comment by arundna** [comment]
@goldbergmoshe - Thanks for raising this issue. As you've already proactively reached out to our UI team on this issue - https://github.com/aws-amplify/amplify-ui/issues/2042, I'll go ahead and close this.

Root Cause - This was a known upstream issue with new version of Error Stack Parser - https://github.com/stacktracejs/error-stack-parser/issues/80.
