### ISSUE TITLE
amplify init does not work on windows 10

### ISSUE THREAD

**Issue by rg3h** [aws-amplify/docs#4528]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/js)

**Feedback**:

amplify init does not work on windows 10
It assumed there was a .aws and a .aws/config directory, issuing a NOENT error. I then made them by hand and it still fails with:
Please choose the profile you want to use default
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:617:3)
    at Object.readSync (pkg/prelude/bootstrap.js:890:32)
    at tryReadSync (fs.js:382:20)
    at Object.readFileSync (fs.js:419:19)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1025:36)
    at Object.readFileSync (C:\snapshot\repo\build\node_modules\aws-sdk\lib\util.js:95:26)
    at IniLoader.parseFile (C:\snapshot\repo\build\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:6:47)
    at IniLoader.loadFrom (C:\snapshot\repo\build\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:56:30)
    at getRegion (C:\snapshot\repo\build\node_modules\aws-sdk\lib\node_loader.js:118:32)
    at Config.region (C:\snapshot\repo\build\node_modules\aws-sdk\lib\node_loader.js:173:18)
    at Config.set (C:\snapshot\repo\build\node_modules\aws-sdk\lib\config.js:524:39)
    at Config.<anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\config.js:359:12)
    at Config.each (C:\snapshot\repo\build\node_modules\aws-sdk\lib\util.js:512:32)
    at new Config (C:\snapshot\repo\build\node_modules\aws-sdk\lib\config.js:358:19)
    at Object.loadServiceClass (C:\snapshot\repo\build\node_modules\aws-sdk\lib\service.js:108:16)
    at Object.Service [as constructor] (C:\snapshot\repo\build\node_modules\aws-sdk\lib\service.js:47:29)
    at new <anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\util.js:629:24)
    at getConfiguredAmplifyClient (C:\snapshot\repo\build\node_modules\amplify-provider-awscloudformation\lib\aws-utils\aws-amplify.js:42:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.init (C:\snapshot\repo\build\node_modules\amplify-provider-awscloudformation\lib\amplify-service-manager.js:51:25)
    at async Object.run (C:\snapshot\repo\build\node_modules\amplify-provider-awscloudformation\lib\initializer.js:135:9) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}

**Comment by rg3h** [comment]
sure thing
Let mecopy it over there.

**Comment by rg3h** [comment]
I moved it over there: https://github.com/aws-amplify/amplify-cli/issues/10889
So we can close it here.
