### ISSUE TITLE
API (GRAPHQL) Getting started Tutorial for JS does not work as written, "No credentials"

### ISSUE THREAD

**Issue by emmby** [aws-amplify/docs#4695]
Following the turorial instructions here: https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js/

1. I followed the prerequisites to Install, configure and init an Amplify project
2. I ran `amplify add api`
3. I ran `amplify push`
4. I ran `npm install aws-amplify` and added the code to my app:
    ```
    import { Amplify, API, graphqlOperation } from 'aws-amplify';
    import awsconfig from './aws-exports';
    Amplify.configure(awsconfig);```
6. I ran the next code in the tutorial:
    ```
    import { API, graphqlOperation } from 'aws-amplify';
    import { createTodo, updateTodo, deleteTodo } from './graphql/mutations';
    
    const todo = { name: "My first todo", description: "Hello world!" };
    
    /* create a todo */
    await API.graphql(graphqlOperation(createTodo, {input: todo}));
    ```


On running the code, I see the following error:
```
background.js:2 [WARN] 59:00.171 GraphQLAPI - ensure credentials error No Cognito Identity pool provided for unauthenticated access
(anonymous) @ background.js:2
14:59:00.171 background.js:2 Uncaught (in promise) Error: No credentials
    at e.<anonymous> (background.js:2:191766)
    at background.js:2:189409
    at Object.next (background.js:2:189514)
    at s (background.js:2:188251)
```




My `aws-exports.js` file looks like the following:
```
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://....appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-..."
};

export default awsmobile;
```

From https://github.com/aws-amplify/docs/issues/1936 I can see that I need to set my API key somewhere, but the documentation mentioned in https://github.com/aws-amplify/docs/issues/1936#issuecomment-644495123 does not say where.

**Comment by emmby** [comment]
User error.

I glossed over one detail in my description. Because I'm using typescript, I was unable to import the aws-exports.js file directly and I used the following instead:
```
const awsconfig = require('./aws-exports');
```
This of course did not work as expected. Changing it to the following fixed the problem:
```
const awsconfig = require('./aws-exports').default;
```
