### ISSUE TITLE
Guide on how to setup custom message Cognito triggers

### ISSUE THREAD

**Issue by nadetastic** [aws-amplify/docs#5100]
**Is your feature request related to a problem? Please describe.**
Currently there doesn't exist a guide that shows how to setup and send custom messages for Cognito triggers. Specifically for [`CustomEmailSender`](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-email-sender.html) and [`CustomSMSSender`](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sms-sender.html)

**Describe the solution you'd like**
A guide that walks through how to use Amplify CLI with `amplify override auth` to set the custom message triggers.

**Describe alternatives you've considered**
N/A

**Additional context**
From the `amplify-js` repo, there is an issue around this scenario where their use case is to use 3rd party providers to send messages, where the provided work around is a short explanation that would be useful as a more detailed guide.

https://github.com/aws-amplify/amplify-js/issues/3099#issuecomment-1386550265

**Comment by wish9919** [comment]
@nadetastic Thanks for considering this request. 
I also had to fulfill the requirement of sending all OTPs through an external provider. I have followed the steps that you mentioned and considered the official docs but there was an error while executing the CustomSMSSender lambda. 

I'm getting this
```json
2023-04-07T17:13:47.381Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "Malformed resource.",
    "stack": [
        "Error: Malformed resource.",
        "    at needs (/var/task/node_modules/@aws-crypto/material-management/build/main/src/needs.js:18:15)",
        "    at parseAwsKmsResource (/var/task/node_modules/@aws-crypto/kms-keyring/build/main/src/arn_parsing.js:94:37)",
        "    at parseAwsKmsKeyArn (/var/task/node_modules/@aws-crypto/kms-keyring/build/main/src/arn_parsing.js:36:9)",
        "    at validAwsKmsIdentifier (/var/task/node_modules/@aws-crypto/kms-keyring/build/main/src/arn_parsing.js:105:13)",
        "    at new KmsKeyring (/var/task/node_modules/@aws-crypto/kms-keyring/build/main/src/kms_keyring.js:32:105)",
        "    at new KmsKeyringNode (/var/task/node_modules/@aws-crypto/kms-keyring-node/build/main/src/kms_keyring_node.js:23:9)",
        "    at Object.<anonymous> (/var/task/index.js:14:17)",
        "    at Module._compile (node:internal/modules/cjs/loader:1165:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1043:32)"
    ]
}
```
I was wondering if it would be possible to provide a guide for setting up and sending custom messages for Cognito triggers. Currently, there is no documentation available, and it would be extremely helpful to have step-by-step instructions for using Amplify CLI with amplify override auth.
