### ISSUE TITLE
init failed Error: Profile configuration is missing for: default     at Object.getProfiledAwsConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/system-config-manager.js:81:11)     at getConfiguredAwsCfnClient (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:65:33)     at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:15:26)     at process._tickCallback (internal/process/next_tick.js:68:7)

### ISSUE THREAD

**Issue by dstrehlow** [aws-amplify/docs#567]
init failed
Error: Profile configuration is missing for: default
    at Object.getProfiledAwsConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/system-config-manager.js:81:11)
    at getConfiguredAwsCfnClient (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:65:33)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:15:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dstrehlow** [comment]
Here's the universal truth:
The documentation is behind.

**Comment by dstrehlow** [comment]
How about a new paradigm:
Documentation Driven Development.

**Comment by jordanranz** [comment]
@dstrehlow, it would help if you posted which part of the docs are behind. Unfortunately just posting an error does not give us enough context to fix and/or reproduce.

**Comment by kaustavghosh06** [comment]
@dstrehlow Please use the latest version of the CLI and check if you're still having this issue. Please feel free to re-open if you're still stuck.
